### ISSUE TITLE
Write some tests

### ISSUE THREAD

**Issue by icaropires** [icaropires/vandor-rename#11]
Would be cool to have some tests for validating the existing functions.

**Comment by suv27** [comment]
- I can help write python scripts, would it be only for `vandor-rename.py` since is the only python file in the repo?
- How would you list it structure?
- I am planning to create a `tests/` folder and write a `<funciton>_test.py` file for each function found in the `vandor-rename.py`

**Comment by icaropires** [comment]
>     * I can help write python scripts, would it be only for `vandor-rename.py` since is the only python file in the repo?
> 
>     * How would you list it structure?
> 
>     * I am planning to create a `tests/` folder and write a `<funciton>_test.py` file for each function found in the `vandor-rename.py`

Hi! Thanks for the interest in contributing :smiley: !
Yes, just for the `vandor-rename.py`.

About the structure, you can create just one file under `tests/` and write all unit tests at this unique file. The intention is to keep one test file for one source file :wink: .

**Comment by suv27** [comment]
When I get all the tests ready I will open a PR, just make sure this issue is assigned to me.
I need to understand the code better

**Comment by suv27** [comment]
Wrote some tests, when I get more chance I will write more. #20

**Comment by suv27** [comment]
I believe you should make issues base on testing each specific function.

**Comment by icaropires** [comment]
> I believe you should make issues base on testing each specific function.

No, I don't think this is a good idea. Only if there were super complex functions. But this is not the case.
