### ISSUE TITLE
Unit test framework and its coverage report

### ISSUE THREAD

**Issue by suv27** [icaropires/vandor-rename#19]
- [x] Create a unit test file that will hold all the tests for each specific function in vandor_rename.py`
> - is_renamed_exercise
> - is_shortname_exercise
> - type_to_presentation_type
> - alert_ignored_files
> - alert_renamings_to_be_applied
> - confirm_operations
> - def rename_files(renamings):
> - parse_files
> - zip_result
> - beg
>  - Code inside of `if __name__ == '__main__':` that should be in ites own function call `main()`

- [x] Create a `coverage report` system for checking the tests coverage of the test when they get implemented

**Comment by icaropires** [comment]
@Physsix27, actually, this issue should be related to what you did at #15 . Just integrating the test framework, the Makefile and the coverage thing. The PR #15 will solve this issue and your new PR (about writing the tests) will solve issue #11 .

Sorry for the misunderstanding !

**Comment by suv27** [comment]
PR #15 Completed which resolves this issue.

**Comment by icaropires** [comment]
> PR #15 Completed which resolves this issue.

Almost there! Take a look at the new review :wink:
